language: node_js

node_js:
  - "7"

branches:
  only:
    - master

before_script:
  - npm install

script:
  - npm run test
  - npm run build

#after_success:
#  - firebase deploy --token $FIREBASE_TOKEN

